-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiKGExtractor/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikikg_snapshot (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_snapshot_hash CHAR(64) NOT NULL,
  wikikg_schema_version BLOB NOT NULL,
  wikikg_metadata BLOB NOT NULL,
  wikikg_created BLOB NOT NULL,
  wikikg_claim_count INTEGER UNSIGNED NOT NULL,
  wikikg_source_count INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(wikikg_snapshot_id)
);

CREATE INDEX wikikg_snapshot_created ON /*_*/wikikg_snapshot (wikikg_created);


CREATE TABLE /*_*/wikikg_source_page (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_page_id INTEGER UNSIGNED NOT NULL,
  wikikg_revision_id INTEGER UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_kind BLOB DEFAULT '' NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_page_id,
    wikikg_revision_id
  )
);


CREATE TABLE /*_*/wikikg_claim (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_semantic_data BLOB NOT NULL,
  wikikg_traceability_complete SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id
  )
);


CREATE TABLE /*_*/wikikg_evidence (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_evidence_id CHAR(64) NOT NULL,
  wikikg_page_id INTEGER UNSIGNED NOT NULL,
  wikikg_revision_id INTEGER UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_extraction_method BLOB NOT NULL,
  wikikg_extractor_version BLOB NOT NULL,
  wikikg_location_type BLOB NOT NULL,
  wikikg_location BLOB DEFAULT NULL,
  wikikg_offset_start INTEGER UNSIGNED DEFAULT NULL,
  wikikg_offset_end INTEGER UNSIGNED DEFAULT NULL,
  wikikg_supporting_span BLOB DEFAULT NULL,
  wikikg_span_hash CHAR(64) DEFAULT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id,
    wikikg_evidence_id
  )
);

CREATE INDEX wikikg_evidence_revision ON /*_*/wikikg_evidence (
  wikikg_snapshot_id, wikikg_page_id,
  wikikg_revision_id
);


CREATE TABLE /*_*/wikikg_review_event (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_version INTEGER UNSIGNED NOT NULL,
  wikikg_reviewer_id INTEGER UNSIGNED NOT NULL,
  wikikg_status BLOB NOT NULL,
  wikikg_reason BLOB NOT NULL,
  wikikg_timestamp BLOB NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_version
  )
);

CREATE INDEX wikikg_review_reviewer_timestamp ON /*_*/wikikg_review_event (
  wikikg_reviewer_id, wikikg_timestamp
);
