-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_claim (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_semantic_data BLOB NOT NULL,
  wikikg_traceability_complete SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id
  )
);
