-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_snapshot (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_snapshot_hash CHAR(64) NOT NULL,
  wikikg_schema_version BLOB NOT NULL,
  wikikg_metadata BLOB NOT NULL,
  wikikg_created BLOB NOT NULL,
  wikikg_claim_count INTEGER UNSIGNED NOT NULL,
  wikikg_source_count INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(wikikg_snapshot_id)
);

CREATE INDEX wikikg_snapshot_created ON /*_*/wikikg_snapshot (wikikg_created);
