-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_review_event (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_version INTEGER UNSIGNED NOT NULL,
  wikikg_reviewer_id INTEGER UNSIGNED NOT NULL,
  wikikg_status BLOB NOT NULL,
  wikikg_reason BLOB NOT NULL,
  wikikg_timestamp BLOB NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_version
  )
);

CREATE INDEX wikikg_review_reviewer_timestamp ON /*_*/wikikg_review_event (
  wikikg_reviewer_id, wikikg_timestamp
);
