-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_evidence (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_evidence_id CHAR(64) NOT NULL,
  wikikg_page_id INTEGER UNSIGNED NOT NULL,
  wikikg_revision_id INTEGER UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_extraction_method BLOB NOT NULL,
  wikikg_extractor_version BLOB NOT NULL,
  wikikg_location_type BLOB NOT NULL,
  wikikg_location BLOB DEFAULT NULL,
  wikikg_offset_start INTEGER UNSIGNED DEFAULT NULL,
  wikikg_offset_end INTEGER UNSIGNED DEFAULT NULL,
  wikikg_supporting_span BLOB DEFAULT NULL,
  wikikg_span_hash CHAR(64) DEFAULT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id,
    wikikg_evidence_id
  )
);

CREATE INDEX wikikg_evidence_revision ON /*_*/wikikg_evidence (
  wikikg_snapshot_id, wikikg_page_id,
  wikikg_revision_id
);
