<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Wikicrop";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wikicrop";

## The protocol and server name to use in fully-qualified URLs
// $wgServer = "http://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/logo_wikicrop.png",
	'icon' => "$wgResourceBasePath/resources/assets/logo_wikicrop.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO
$wgPasswordSender = "YOUR_EMAIL";

$wgSMTP = [
    'host' => 'ssl://smtp.gmail.com', // Gmail SMTP Server
    'port' => 465,
    'IDHost' => 'localhost',
    'auth' => true,
    'username' => 'YOUR_EMAIL', // Your full Gmail address
    'password' => 'YOUR_GOOGLE_APP_PASSWORD' // The App Password you generated
];

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "mediawiki_new1";
$wgDBuser = "root";
$wgDBpassword = "";

// Để máy khác cũng vào được và đã tắt // $wgServer = "http://localhost";
$protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? "https://" : "http://";
$host = $_SERVER['HTTP_HOST'];
$wgServer = $protocol . $host;

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "vi"; // Thiết lập ngôn ngữ mặc định của wiki là tiếng Việt (vi)
$wgShellLocale = "C.UTF-8";

#$wgShellLocale = "vi_VN.UTF-8";

# Time zone
$wgLocaltimezone = "Europe/Berlin";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "f87644f0b1ebbd45885b2ef166fbed53253d0260418fa9257917c05cda619e30";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a2118201b0d28666";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["createaccount"] = true;
$wgGroupPermissions["*"]["edit"] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
#$wgDefaultSkin = "vector"; 
$wgDefaultSkin = "vector-2022"; #sửa từ $wgDefaultSkin = "vector"; 


# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:

wfLoadExtension( 'AbuseFilter' ); 
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' ); 
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'DiscussionTools' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'LoginNotify' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'UniversalLanguageSelector' );
wfLoadExtension( 'Translate' );
#wfLoadExtension( 'ContentTranslation' );

#wfLoadExtension( 'Popups' );


# End of automatically generated settings.
# Add more configuration options below.

// Bật tính năng dịch trang
$wgEnablePageTranslation = true;
//$wgPageTranslationLanguageList = ['vi', 'en']; // Ngôn ngữ hỗ trợ

// Cấu hình ngôn ngữ hệ thống
// $wgLanguageCode = 'vi'; // Ngôn ngữ mặc định (tiếng Việt)
$wgDefaultLanguageVariant = 'vi';

// Cấu hình Universal Language Selector
$wgULSEnable = true;
$wgULSPosition = 'interlanguage'; // Vị trí selector ngôn ngữ
$wgULSGeoService = 'geoiplookup'; // Xác định ngôn ngữ theo vị trí địa lý
$wgULSAnonCanChangeLanguage = true; // Cho phép đổi ngôn ngữ khi chưa đăng nhập
$wgULSLanguageDetection = ['cookie', 'url', 'browser']; // Cách phát hiện ngôn ngữ

// Cấu hình Translate Extension
//$wgTranslateLanguageCodes = ['vi', 'en']; // Ngôn ngữ hỗ trợ dịch
$wgTranslateSupportedLanguages = ['en'];
$wgTranslateLanguageFallbacks['en'] = 'vi';

$wgAvailableLanguages = ['vi', 'en'];
$wgTranslateDocumentationLanguageCode = 'qqq';


$wgTranslateTranslationServices = [
    'TTMServer' => [
        'database' => false,
        'cutoff' => 0.75,
    ],
];
$wgTranslateDocumentationLanguageCode = 'qqq';

// Phân quyền dịch thuật
$wgGroupPermissions['user']['translate'] = true;
$wgGroupPermissions['translator']['translate'] = true;
$wgGroupPermissions['translator']['pagetranslation'] = true;
$wgGroupPermissions['sysop']['pagetranslation'] = true;

// Cấu hình Content Translation
$wgContentTranslationEnableApi = true;
$wgContentTranslationTranslateInTarget = true;
$wgContentTranslationSiteTemplates = [
    'wikipedia' => 'https://$1.wikipedia.org/wiki/$2',
];

// Không gian tên cho phép dịch
$wgContentTranslationNamespaceInclude = [
    NS_MAIN,
    NS_TALK,
    // ... (giữ nguyên các namespace khác)
];

// Cấu hình hiệu năng
$wgTranslateKeepMessages = true;
$wgTranslateSecondaryPermission = 'translate';

// Tự động chọn ngôn ngữ nội dung
$wgULSContentLanguageSelector = true;
$wgPageLanguageUseDB = true;

// Cấu hình ngôn ngữ mặc định
$wgDefaultUserOptions['language'] = 'vi';
$wgDefaultUserOptions['variant'] = 'vi';

// ========== CẤU HÌNH GỠ LỖI ========== //
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;


$wgRawHtml = true;


$wgVectorShowSkinPreferences = true; // Hiện tùy chọn skin trong giao diện người dùng
$wgVectorUseSidebarSearch = true;    // Sử dụng thanh tìm kiếm ở thanh bên
$wgVectorUsePageTabsForNamespaces = true; // Dùng tab để phân biệt namespace
// ========== CẤU HÌNH SERVER & DỊCH VỤ (CHỈNH TẠI ĐÂY) ==========
// Có thể thay đổi localhost thành IP hoặc tên miền khi deploy (ví dụ: '192.168.1.10' hoặc 'wikicrop.vn')
$wgAppLocalHost = 'localhost'; 

// 1. Cấu hình Chatbot Server
$wgChatbotServerUrl = "http://$wgAppLocalHost:8000";
$wgWikiChatbotApiUrl = "$wgChatbotServerUrl/ask";
$wgApproveChatbotIngestUrl = "$wgChatbotServerUrl/ingest";

// 2. Cấu hình Keycloak Server
$wgKeycloakServerUrl = "http://$wgAppLocalHost:8090";

// 3. Cấu hình JupyterHub (nếu cần)
$wgJupyterHubUrl = "http://$wgAppLocalHost:9090/hub";
// ==============================================================


### Nguyen Huu Dat, TTTT HK3 2024-2025
// Custom wikitext tag, goi api endpoint hien thi reponse
wfLoadExtension( 'ApiData' );

// Them donate button vao sidebar
wfLoadExtension( 'DonateButton' );
$wgDonateButton = true;
$wgDonateButtonURL = "https://example.org";

// Tich hop keycloack
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'OpenIDConnect' );

$wgPluggableAuth_Config['Keycloak Login'] = [
    'plugin' => 'OpenIDConnect',
    'data' => [
        'providerURL' => "$wgKeycloakServerUrl/realms/my_realm", // Thay thế 'my_realm' bằng tên realm của bạn
        'clientID' => 'YOUR_CLIENT_ID', // Thay thế bằng client ID của bạn
        'clientsecret' => 'YOUR_KEYCLOAK_CLIENT_SECRET', // Thay thế bằng client secret của bạn
    ],
    'groupsyncs' => [
        'sync_from_keycloak' => [ 
            'type' => 'syncall',
            'groupAttributeName' => 'groups',
            'groupAttributeDelimiter' => ',',
            'locallyManaged' => [ 'bureaucrat' ], // Nhóm do wiki tự quản lý
        ]
    ]
];


unset( $wgFooterIcons['poweredby'] );

$wgOpenIDConnect_SingleLogout = true; // Dang xuat hoan toan
$wgGroupPermissions['*']['autocreateaccount'] = true;
// $wgDBserver = "127.0.0.1:3306"; // Can de update db cho OpenIDConnect

wfLoadExtension( 'Approve' );
wfLoadExtension( 'WikiChatbot' );
$wgWikichatbot = true;
$wgWikichatbotEnabled = true;

$wgGroupPermissions['approver']['approverevisions'] = true;
$wgGroupPermissions['sysop']['approverevisions'] = true;


wfLoadExtension( 'ApiPlantDB' );
// wfLoadExtension( 'MicrosoftClarity' );
// $wgMicrosoftClarityID = 'YOUR_CLARITY_ID'; // Thay thế bằng Clarity ID

// Thesis graph integration is intentionally opt-in.
// wfLoadExtension( 'WikiKGExtractor' );
// $wgWikiKGExtractorEnableKG = false;
// $wgWikiKGExtractorPushToNeo4j = false;

wfLoadExtension( 'NongNghiep40' );
wfLoadExtension( 'QuanLyNongNghiep40' );
$wgQuanLyNongNghiep40GeminiKey = 'GEMINI_API_KEY'; // Thay thế bằng Gemini Key của bạn

wfLoadExtension( 'ReplaceText' );
