-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiKGExtractor/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikikg_snapshot (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_snapshot_hash CHAR(64) NOT NULL,
  wikikg_schema_version VARBINARY(8) NOT NULL,
  wikikg_metadata BLOB NOT NULL,
  wikikg_created BINARY(14) NOT NULL,
  wikikg_claim_count INT UNSIGNED NOT NULL,
  wikikg_source_count INT UNSIGNED NOT NULL,
  INDEX wikikg_snapshot_created (wikikg_created),
  PRIMARY KEY(wikikg_snapshot_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikikg_source_page (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_page_id INT UNSIGNED NOT NULL,
  wikikg_revision_id INT UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_kind VARBINARY(16) DEFAULT '' NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_page_id,
    wikikg_revision_id
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikikg_claim (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_semantic_data BLOB NOT NULL,
  wikikg_traceability_complete TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikikg_evidence (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_evidence_id CHAR(64) NOT NULL,
  wikikg_page_id INT UNSIGNED NOT NULL,
  wikikg_revision_id INT UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_extraction_method VARBINARY(8) NOT NULL,
  wikikg_extractor_version VARBINARY(64) NOT NULL,
  wikikg_location_type VARBINARY(16) NOT NULL,
  wikikg_location BLOB DEFAULT NULL,
  wikikg_offset_start INT UNSIGNED DEFAULT NULL,
  wikikg_offset_end INT UNSIGNED DEFAULT NULL,
  wikikg_supporting_span BLOB DEFAULT NULL,
  wikikg_span_hash CHAR(64) DEFAULT NULL,
  INDEX wikikg_evidence_revision (
    wikikg_snapshot_id, wikikg_page_id,
    wikikg_revision_id
  ),
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id,
    wikikg_evidence_id
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikikg_review_event (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_version INT UNSIGNED NOT NULL,
  wikikg_reviewer_id INT UNSIGNED NOT NULL,
  wikikg_status VARBINARY(8) NOT NULL,
  wikikg_reason BLOB NOT NULL,
  wikikg_timestamp BINARY(14) NOT NULL,
  INDEX wikikg_review_reviewer_timestamp (
    wikikg_reviewer_id, wikikg_timestamp
  ),
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_version
  )
) /*$wgDBTableOptions*/;
