-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_source_page (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_page_id INT UNSIGNED NOT NULL,
  wikikg_revision_id INT UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_kind VARBINARY(16) DEFAULT '' NOT NULL,
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_page_id,
    wikikg_revision_id
  )
) /*$wgDBTableOptions*/;
