-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_review_event (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_version INT UNSIGNED NOT NULL,
  wikikg_reviewer_id INT UNSIGNED NOT NULL,
  wikikg_status VARBINARY(8) NOT NULL,
  wikikg_reason BLOB NOT NULL,
  wikikg_timestamp BINARY(14) NOT NULL,
  INDEX wikikg_review_reviewer_timestamp (
    wikikg_reviewer_id, wikikg_timestamp
  ),
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_version
  )
) /*$wgDBTableOptions*/;
