-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_evidence (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_claim_id CHAR(64) NOT NULL,
  wikikg_evidence_id CHAR(64) NOT NULL,
  wikikg_page_id INT UNSIGNED NOT NULL,
  wikikg_revision_id INT UNSIGNED NOT NULL,
  wikikg_content_hash CHAR(64) NOT NULL,
  wikikg_page_title BLOB NOT NULL,
  wikikg_extraction_method VARBINARY(8) NOT NULL,
  wikikg_extractor_version VARBINARY(64) NOT NULL,
  wikikg_location_type VARBINARY(16) NOT NULL,
  wikikg_location BLOB DEFAULT NULL,
  wikikg_offset_start INT UNSIGNED DEFAULT NULL,
  wikikg_offset_end INT UNSIGNED DEFAULT NULL,
  wikikg_supporting_span BLOB DEFAULT NULL,
  wikikg_span_hash CHAR(64) DEFAULT NULL,
  INDEX wikikg_evidence_revision (
    wikikg_snapshot_id, wikikg_page_id,
    wikikg_revision_id
  ),
  PRIMARY KEY(
    wikikg_snapshot_id, wikikg_claim_id,
    wikikg_evidence_id
  )
) /*$wgDBTableOptions*/;
