-- Generated by tools/split_schema_sql.py from tables-generated.sql. Do not edit directly.
CREATE TABLE /*_*/wikikg_snapshot (
  wikikg_snapshot_id CHAR(64) NOT NULL,
  wikikg_snapshot_hash CHAR(64) NOT NULL,
  wikikg_schema_version VARBINARY(8) NOT NULL,
  wikikg_metadata BLOB NOT NULL,
  wikikg_created BINARY(14) NOT NULL,
  wikikg_claim_count INT UNSIGNED NOT NULL,
  wikikg_source_count INT UNSIGNED NOT NULL,
  INDEX wikikg_snapshot_created (wikikg_created),
  PRIMARY KEY(wikikg_snapshot_id)
) /*$wgDBTableOptions*/;
