services:
  mediawiki:
    platform: linux/amd64
    image: wikicrop-kg-demo-mediawiki:2.3.0
    build:
      context: .
      dockerfile: extensions/WikiKGExtractor/demo/python3.dockerfile
  mediawiki-web:
    platform: linux/amd64
    ports: !override
      - "127.0.0.1:${MW_DOCKER_PORT:-8088}:8080"
