#!/usr/bin/env python3
"""Split MediaWiki's generated aggregate SQL into table-specific updater patches."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


EXTENSION_ROOT = Path(__file__).resolve().parents[1]
EXPECTED_TABLES = (
    "wikikg_snapshot",
    "wikikg_source_page",
    "wikikg_claim",
    "wikikg_evidence",
    "wikikg_review_event",
)
PATCH_HEADER = (
    "-- Generated by tools/split_schema_sql.py from tables-generated.sql. "
    "Do not edit directly.\n"
)
TABLE_RE = re.compile(
    r"^CREATE\s+TABLE\s+/\*_\*/(?P<table>[A-Za-z_][A-Za-z0-9_]*)\b",
    re.IGNORECASE,
)
INDEX_RE = re.compile(
    r"^CREATE\s+(?:UNIQUE\s+)?INDEX\s+"
    r"(?P<index>[A-Za-z_][A-Za-z0-9_]*)\s+ON\s+/\*_\*/"
    r"(?P<table>[A-Za-z_][A-Za-z0-9_]*)\s*\(",
    re.IGNORECASE,
)


def expected_schema() -> tuple[tuple[str, ...], dict[str, str]]:
    schema_path = EXTENSION_ROOT / "sql" / "tables.json"
    try:
        tables = json.loads(schema_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read schema source {schema_path}: {error}") from error

    if not isinstance(tables, list):
        raise ValueError(f"{schema_path} must contain a list of tables")
    names = tuple(table.get("name") for table in tables if isinstance(table, dict))
    if len(names) != len(tables) or names != EXPECTED_TABLES:
        raise ValueError(
            "sql/tables.json must define exactly these tables in order: "
            + ", ".join(EXPECTED_TABLES)
        )

    indexes: dict[str, str] = {}
    for table in tables:
        table_name = table["name"]
        table_indexes = table.get("indexes", [])
        if not isinstance(table_indexes, list):
            raise ValueError(f"indexes for {table_name} must be a list")
        for index in table_indexes:
            if not isinstance(index, dict) or not isinstance(index.get("name"), str):
                raise ValueError(f"invalid index definition for {table_name}")
            index_name = index["name"]
            if index_name in indexes:
                raise ValueError(f"duplicate index name in sql/tables.json: {index_name}")
            indexes[index_name] = table_name
    return names, indexes


def split_statements(sql: str, source: str) -> list[str]:
    """Split on SQL semicolons outside quoted values and comments."""
    statements: list[str] = []
    start = 0
    quote: str | None = None
    line_comment = False
    block_comment = False
    index = 0

    while index < len(sql):
        char = sql[index]
        next_char = sql[index + 1] if index + 1 < len(sql) else ""

        if line_comment:
            if char == "\n":
                line_comment = False
        elif block_comment:
            if char == "*" and next_char == "/":
                block_comment = False
                index += 1
        elif quote:
            if char == "\\" and quote in "\"'" and next_char:
                index += 1
            elif char == quote:
                if next_char == quote:
                    index += 1
                else:
                    quote = None
        elif char in "\"'`":
            quote = char
        elif char == "/" and next_char == "*":
            block_comment = True
            index += 1
        elif char == "#" or (char == "-" and next_char == "-"):
            line_comment = True
            if char == "-":
                index += 1
        elif char == ";":
            statement = sql[start : index + 1].strip()
            if statement:
                statements.append(statement)
            start = index + 1
        index += 1

    if quote:
        raise ValueError(f"{source}: unterminated quoted value")
    if block_comment:
        raise ValueError(f"{source}: unterminated block comment")
    if sql[start:].strip():
        raise ValueError(f"{source}: unexpected text after the final SQL semicolon")
    return statements


def without_leading_comments(statement: str, source: str) -> str:
    """Remove generated file banners before classifying a SQL statement."""
    position = 0
    while position < len(statement):
        while position < len(statement) and statement[position].isspace():
            position += 1
        if statement.startswith("--", position) or statement.startswith("#", position):
            newline = statement.find("\n", position)
            position = len(statement) if newline < 0 else newline + 1
        elif statement.startswith("/*", position):
            end = statement.find("*/", position + 2)
            if end < 0:
                raise ValueError(f"{source}: unterminated leading comment")
            position = end + 2
        else:
            break
    return statement[position:].lstrip()


def parse_generated_sql(
    db_type: str, sql: str, expected_tables: tuple[str, ...], indexes: dict[str, str]
) -> dict[str, str]:
    source = f"sql/{db_type}/tables-generated.sql"
    statements = split_statements(sql, source)
    patches = {table: [] for table in expected_tables}
    actual_order: list[tuple[str, str, str | None]] = []
    created_tables: set[str] = set()

    for number, statement in enumerate(statements, start=1):
        body = without_leading_comments(statement, source)
        table_match = TABLE_RE.match(body)
        if table_match:
            table = table_match.group("table")
            if table not in patches:
                raise ValueError(f"{source}: unexpected table in statement {number}: {table}")
            if table in created_tables:
                raise ValueError(f"{source}: duplicate CREATE TABLE for {table}")
            created_tables.add(table)
            actual_order.append(("table", table, None))
            patches[table].append(body.rstrip())
            continue

        index_match = INDEX_RE.match(body)
        if index_match and db_type == "sqlite":
            index_name = index_match.group("index")
            table = index_match.group("table")
            if indexes.get(index_name) != table:
                raise ValueError(
                    f"{source}: unexpected index {index_name} on table {table} "
                    f"in statement {number}"
                )
            if table not in created_tables:
                raise ValueError(
                    f"{source}: index {index_name} appears before table {table}"
                )
            if any(item[0] == "index" and item[1] == index_name for item in actual_order):
                raise ValueError(f"{source}: duplicate CREATE INDEX for {index_name}")
            actual_order.append(("index", index_name, table))
            patches[table].append(body.rstrip())
            continue

        preview = " ".join(body.split())[:80]
        raise ValueError(
            f"{source}: unexpected SQL in statement {number}: {preview or '<empty>'}"
        )

    expected_order: list[tuple[str, str, str | None]] = []
    for table in expected_tables:
        expected_order.append(("table", table, None))
        if db_type == "sqlite":
            expected_order.extend(
                ("index", name, table)
                for name, index_table in indexes.items()
                if index_table == table
            )
    if actual_order != expected_order:
        expected = ", ".join(item[1] for item in expected_order)
        actual = ", ".join(item[1] for item in actual_order)
        raise ValueError(
            f"{source}: SQL statement order/content does not match schema; "
            f"expected [{expected}], found [{actual}]"
        )

    return {table: "\n\n".join(parts) + "\n" for table, parts in patches.items()}


def generated_patches() -> dict[Path, str]:
    tables, indexes = expected_schema()
    generated: dict[Path, str] = {}
    for db_type in ("mysql", "sqlite"):
        aggregate = EXTENSION_ROOT / "sql" / db_type / "tables-generated.sql"
        try:
            sql = aggregate.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as error:
            raise ValueError(f"cannot read generated aggregate {aggregate}: {error}") from error
        patches = parse_generated_sql(db_type, sql, tables, indexes)
        for table, body in patches.items():
            path = EXTENSION_ROOT / "sql" / db_type / f"{table}-generated.sql"
            generated[path] = PATCH_HEADER + body
    return generated


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Split MediaWiki's MySQL and SQLite generated SQL aggregates into table patches."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated table patches without writing files",
    )
    args = parser.parse_args()

    try:
        generated = generated_patches()
    except ValueError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            stale = [
                path
                for path, contents in generated.items()
                if not path.is_file() or path.read_text(encoding="utf-8") != contents
            ]
        except (OSError, UnicodeError) as error:
            print(f"Error: cannot read generated schema patch: {error}", file=sys.stderr)
            return 1
        if stale:
            print(
                "Error: missing or stale schema patches: "
                + ", ".join(str(path.relative_to(EXTENSION_ROOT)) for path in stale),
                file=sys.stderr,
            )
            return 1
        print("Schema patches are current.")
        return 0

    try:
        for path, contents in generated.items():
            path.write_text(contents, encoding="utf-8")
    except OSError as error:
        print(f"Error: cannot write generated schema patch: {error}", file=sys.stderr)
        return 1
    print(f"Generated {len(generated)} table-specific schema patches.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
